version: "3"

services:

  # 1) first build the imaghe
  # > docker compose build
  build:
    image: autobackup
    build:
      dockerfile: Dockerfile
      context: .

  # 2) Configure meocloud (if not needed, just set USE_MEOCLOUD to "0" below, or comment the line)
  # Create empty meocloud config:
  # > touch /mnt/backup/meocloud.conf 
  # initiate meocloud config
  # > docker compose run --rm init
  init:
    image: autobackup
    environment:
      TZ: Europe/Lisbon #changeme
    command: "meocloud --init"

    volumes:
      - /mnt/backup/meocloud.conf:/etc/meocloud.conf

  # 3) start backing up (check abackup_schedule.sh cron.d examples for usage)
  # > docker compose run --rm backup ... 
  backup:
    image: autobackup
    hostname: serverd #changeme
    environment:
      TZ: Europe/Lisbon #changeme
      USE_MEOCLOUD: "1" # change to zero if not needed, or comment the line
    volumes:
      - /mnt/backup/config:/app/config
      - /mnt/backup/store:/store
      - /mnt/backup/meocloud.conf:/etc/meocloud.conf
      - /var/log:/backup/var/log:ro
      - /etc:/backup/etc:ro
      # mount whatever you want to be backed up from the host into /backup/...
